language: cpp
sudo: required
dist: trusty
os:
  - linux
compiler:
  - gcc

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/ppa
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get -y -qq update
  - sudo apt install gcc-defaults
  - sudo apt-get -y -qq upgrade
  - sudo apt install -y qtbase5-dev qtdeclarative5-dev
  - sudo apt install -y qt5-default qttools5-dev-tools

before_script:
  - qmake

script:
  - make
  - ./test/tst_testtest
